# Buildspec runs in the build stage of your environment pipeline to generate environment + service CloudFormation stacks.
version: 0.2

phases:
  install:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd "$CODEBUILD_SRC_DIR"
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.34.1
      - mv ./copilot-linux-v1.34.1 ./copilot-linux
      - chmod +x ./copilot-linux
      - ./copilot-linux --version

  build:
    commands:
      - echo "Run your tests"
      # - make test

  post_build:
    commands:
      - set -euo pipefail
      - export COLOR="false"
      - export CI="true"
      - mkdir -p infrastructure
      - echo "Packaging environment + api service for dev..."
      - 'env="dev"; ./copilot-linux env package -n "$env" --output-dir "./infrastructure" --upload-assets'
      - 'env="dev"; ./copilot-linux svc package -n "api" -e "$env" --output-dir "./infrastructure" --upload-assets'
      - echo "Generated artifacts:"
      - ls -lah ./infrastructure

artifacts:
  files:
    - "infrastructure/*"
